//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 12:56:55 PM CET 
//

package be.jsams.server.model.xml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}phone"/>
 *         &lt;element ref="{}fax"/>
 *         &lt;element ref="{}mobile"/>
 *         &lt;element ref="{}email"/>
 *         &lt;element ref="{}website"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "phone", "fax", "mobile", "email", "website" })
@XmlRootElement(name = "contact_info")
public class ContactInformationXml {

    @XmlElement(required = true)
    private BigInteger phone;
    @XmlElement(required = true)
    private BigInteger fax;
    @XmlElement(required = true)
    private String mobile;
    @XmlElement(required = true)
    private String email;
    @XmlElement(required = true)
    private String website;

    /**
     * Gets the value of the phone property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setPhone(BigInteger value) {
        this.phone = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setFax(BigInteger value) {
        this.fax = value;
    }

    /**
     * Gets the value of the mobile property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * Sets the value of the mobile property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMobile(String value) {
        this.mobile = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setWebsite(String value) {
        this.website = value;
    }

}
