//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 04:12:39 PM CET 
//

package be.jsams.server.model.xml.bill;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import be.jsams.server.model.xml.ProductXml;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}product"/>
 *         &lt;element ref="{}quantity"/>
 *         &lt;element ref="{}price"/>
 *         &lt;element ref="{}discount_rate"/>
 *         &lt;element ref="{}total_et"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "product", "quantity", "price", "discountRate", "totalEt" })
@XmlRootElement(name = "detail")
public class DetailXml {

    @XmlElement(required = true)
    private ProductXml product;
    @XmlElement(required = true)
    private BigInteger quantity;
    @XmlElement(required = true)
    private BigDecimal price;
    @XmlElement(name = "discount_rate", required = true)
    private BigDecimal discountRate;
    @XmlElement(name = "total_et", required = true)
    private BigDecimal totalEt;

    /**
     * Gets the value of the product property.
     * 
     * @return possible object is {@link ProductXml }
     * 
     */
    public ProductXml getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value allowed object is {@link ProductXml }
     * 
     */
    public void setProduct(ProductXml value) {
        this.product = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setQuantity(BigInteger value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the discountRate property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getDiscountRate() {
        return discountRate;
    }

    /**
     * Sets the value of the discountRate property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setDiscountRate(BigDecimal value) {
        this.discountRate = value;
    }

    /**
     * Gets the value of the totalEt property.
     * 
     * @return possible object is {@link BigDecimal }
     * 
     */
    public BigDecimal getTotalEt() {
        return totalEt;
    }

    /**
     * Sets the value of the totalEt property.
     * 
     * @param value allowed object is {@link BigDecimal }
     * 
     */
    public void setTotalEt(BigDecimal value) {
        this.totalEt = value;
    }

}
