//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.21 at 08:29:51 PM CEST 
//


package be.jsams.server.xml.estimate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zip_QNAME = new QName("", "zip");
    private final static QName _Phone_QNAME = new QName("", "phone");
    private final static QName _Fax_QNAME = new QName("", "fax");
    private final static QName _Website_QNAME = new QName("", "website");
    private final static QName _Street_QNAME = new QName("", "street");
    private final static QName _TotalEt_QNAME = new QName("", "total_et");
    private final static QName _Vat_QNAME = new QName("", "vat");
    private final static QName _Number_QNAME = new QName("", "number");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _CreationDate_QNAME = new QName("", "creation_date");
    private final static QName _FirstName_QNAME = new QName("", "first_name");
    private final static QName _Price_QNAME = new QName("", "price");
    private final static QName _VatNumber_QNAME = new QName("", "vat_number");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _TotalAti_QNAME = new QName("", "total_ati");
    private final static QName _Quantity_QNAME = new QName("", "quantity");
    private final static QName _Mobile_QNAME = new QName("", "mobile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SocietyXml }
     * 
     */
    public SocietyXml createSociety() {
        return new SocietyXml();
    }

    /**
     * Create an instance of {@link CustomerXml }
     * 
     */
    public CustomerXml createCustomer() {
        return new CustomerXml();
    }

    /**
     * Create an instance of {@link EstimateXml }
     * 
     */
    public EstimateXml createEstimate() {
        return new EstimateXml();
    }

    /**
     * Create an instance of {@link ProductXml }
     * 
     */
    public ProductXml createProduct() {
        return new ProductXml();
    }

    /**
     * Create an instance of {@link DetailXml }
     * 
     */
    public DetailXml createDetail() {
        return new DetailXml();
    }

    /**
     * Create an instance of {@link DetailsXml }
     * 
     */
    public DetailsXml createDetails() {
        return new DetailsXml();
    }

    /**
     * Create an instance of {@link AddressXml }
     * 
     */
    public AddressXml createAddress() {
        return new AddressXml();
    }

    /**
     * Create an instance of {@link ContactInfoXml }
     * 
     */
    public ContactInfoXml createContactInfo() {
        return new ContactInfoXml();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zip")
    public JAXBElement<Object> createZip(Object value) {
        return new JAXBElement<Object>(_Zip_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone")
    public JAXBElement<Object> createPhone(Object value) {
        return new JAXBElement<Object>(_Phone_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fax")
    public JAXBElement<Object> createFax(Object value) {
        return new JAXBElement<Object>(_Fax_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "website")
    public JAXBElement<Object> createWebsite(Object value) {
        return new JAXBElement<Object>(_Website_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "street")
    public JAXBElement<String> createStreet(String value) {
        return new JAXBElement<String>(_Street_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "total_et")
    public JAXBElement<Double> createTotalEt(Double value) {
        return new JAXBElement<Double>(_TotalEt_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vat")
    public JAXBElement<Double> createVat(Double value) {
        return new JAXBElement<Double>(_Vat_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number")
    public JAXBElement<Integer> createNumber(Integer value) {
        return new JAXBElement<Integer>(_Number_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creation_date")
    public JAXBElement<XMLGregorianCalendar> createCreationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreationDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first_name")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "price")
    public JAXBElement<Double> createPrice(Double value) {
        return new JAXBElement<Double>(_Price_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "vat_number")
    public JAXBElement<String> createVatNumber(String value) {
        return new JAXBElement<String>(_VatNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<Object> createEmail(Object value) {
        return new JAXBElement<Object>(_Email_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "total_ati")
    public JAXBElement<Double> createTotalAti(Double value) {
        return new JAXBElement<Double>(_TotalAti_QNAME, Double.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "quantity")
    public JAXBElement<Short> createQuantity(Short value) {
        return new JAXBElement<Short>(_Quantity_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mobile")
    public JAXBElement<Object> createMobile(Object value) {
        return new JAXBElement<Object>(_Mobile_QNAME, Object.class, null, value);
    }

}
