CREATE TABLE COMMAND_DETAIL
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	QUANTITY BIGINT NOT NULL,
	PRICE REAL(12,2) NOT NULL,
	VAT_APPLICABLE REAL(5,2) NOT NULL,
	DISCOUNT_RATE REAL(5,2),
	TRANSFERRED BOOL,
	FK_COMMAND BIGINT NOT NULL,
	FK_PRODUCT BIGINT NOT NULL,
	PRIMARY KEY (ID, FK_COMMAND)
) ENGINE = InnoDB;

ALTER TABLE COMMAND_DETAIL
	ADD FOREIGN KEY (FK_COMMAND)
	REFERENCES COMMAND (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE COMMAND_DETAIL
	ADD FOREIGN KEY (FK_PRODUCT)
	REFERENCES PRODUCT (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;