CREATE TABLE BTS.DELIVERY_ORDER_DETAIL
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	QUANTITY INT NOT NULL,
	DESCRIPTION VARCHAR(100),
	VAT_APPLICABLE REAL(5,2),
	DISCOUNT_RATE REAL(5,2),
	TRANSFERRED BOOL,
	FK_DELIVERY_ORDER BIGINT NOT NULL,
	FK_PRODUCT BIGINT NOT NULL,
	FK_COMMAND_DETAIL BIGINT NOT NULL,
	FK_COMMAND BIGINT NOT NULL,
	FK_BILL_DETAIL BIGINT,
	FK_BILL BIGINT,
	PRIMARY KEY (ID, FK_DELIVERY_ORDER)
) ENGINE = InnoDB;

ALTER TABLE BTS.DELIVERY_ORDER_DETAIL
	ADD FOREIGN KEY (FK_COMMAND_DETAIL, FK_COMMAND)
	REFERENCES BTS.COMMAND_DETAIL (ID, FK_COMMAND)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.DELIVERY_ORDER_DETAIL
	ADD FOREIGN KEY (FK_DELIVERY_ORDER)
	REFERENCES BTS.DELIVERY_ORDER (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.DELIVERY_ORDER_DETAIL
	ADD FOREIGN KEY (FK_PRODUCT)
	REFERENCES BTS.PRODUCT (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.DELIVERY_ORDER_DETAIL
	ADD FOREIGN KEY (FK_BILL_DETAIL, FK_BILL)
	REFERENCES BTS.BILL_DETAIL (ID, FK_BILL)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;
