CREATE TABLE BTS.BILL
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CREATION_DATE DATE NOT NULL,
	REMARK VARCHAR(100),
	DISCOUNT_RATE REAL(5,2),
	DUE_DATE DATE NOT NULL,
	PAID BOOL,
	DATE_FIRST_REMINDER DATE NOT NULL,
	DATE_SECOND_REMINDER DATE NOT NULL,
	DATE_FORMAL_NOTICE DATE NOT NULL,
	CLOSED BOOL,
	FK_PAYMENT_MODE BIGINT NOT NULL,
	FK_CUSTOMER BIGINT NOT NULL,
	FK_ADDRESS_BILLING BIGINT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB;

ALTER TABLE BTS.BILL
	ADD FOREIGN KEY (FK_ADDRESS_BILLING)
	REFERENCES BTS.ADDRESS (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.BILL
	ADD FOREIGN KEY (FK_CUSTOMER)
	REFERENCES BTS.CUSTOMER (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.BILL
	ADD FOREIGN KEY (FK_PAYMENT_MODE)
	REFERENCES BTS.PAYMENT_MODE (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;
