CREATE TABLE `bts`.`SOCIETY` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `LABEL` VARCHAR(100) NOT NULL,
  `CAPITAL` DECIMAL(10,2) NOT NULL,
  `ACTIVITY` VARCHAR(100) NOT NULL,
  `RESPONSIBLE` VARCHAR(100) NOT NULL,
  `STREET` VARCHAR(100) NOT NULL,
  `NUMBER` VARCHAR(100) NOT NULL,
  `ZIPCODE` INTEGER(10) UNSIGNED NOT NULL,
  `BOX` VARCHAR(100) NOT NULL,
  `CITY` VARCHAR(100) NOT NULL,
  `COUNTRY` VARCHAR(100) NOT NULL,
  `PHONE` VARCHAR(45) NOT NULL,
  `FAX` VARCHAR(45) NOT NULL,
  `GSM` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `WEBSITE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_LEGAL_FORM` FOREIGN KEY `FK_LEGAL_FORM` (`ID`)
    REFERENCES `legal_form` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;