CREATE TABLE BTS.ESTIMATE_DETAIL
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	QUANTITY BIGINT NOT NULL,
	PRICE REAL(12,2) NOT NULL,
	VAT_APPLICABLE REAL(5,2),
	DISCOUNT_RATE REAL(5,2),
	TRANSFERRED BOOL,
	FK_ESTIMATE BIGINT NOT NULL,
	FK_PRODUCT BIGINT NOT NULL,
	PRIMARY KEY (ID, FK_ESTIMATE)
) ENGINE = InnoDB;

ALTER TABLE BTS.ESTIMATE_DETAIL
	ADD FOREIGN KEY (FK_ESTIMATE)
	REFERENCES BTS.ESTIMATE (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.ESTIMATE_DETAIL
	ADD FOREIGN KEY (FK_PRODUCT)
	REFERENCES BTS.PRODUCT (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;
