CREATE TABLE BTS.CUSTOMER
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	VAT_NUMBER VARCHAR(50),
	DEFAULT_DISCOUNT_RATE REAL(5,2),
	BANK_1 VARCHAR(100),
	BANK_2 VARCHAR(100),
	CREDIT_LIMIT REAL(12,2),
	VAT_APPLICABLE REAL(5,2),
	DESCRIPTION VARCHAR(100),
	FK_ADDRESS_DELIVERY BIGINT NOT NULL,
	FK_ADDRESS_BILLING BIGINT NOT NULL,
	FK_PAYMENT_MODE BIGINT NOT NULL,
	FK_CONTACT_INFORMATION BIGINT NOT NULL,
	FK_CIVILITY BIGINT,
	FK_LEGAL_FORM BIGINT,
	PRIMARY KEY (ID)
) ENGINE = InnoDB;

ALTER TABLE BTS.CUSTOMER
	ADD FOREIGN KEY (FK_ADDRESS_BILLING)
	REFERENCES BTS.ADDRESS (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.CUSTOMER
	ADD FOREIGN KEY (FK_ADDRESS_DELIVERY)
	REFERENCES BTS.ADDRESS (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.CUSTOMER
	ADD FOREIGN KEY (FK_CIVILITY)
	REFERENCES BTS.CIVILITY (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.CUSTOMER
	ADD FOREIGN KEY (FK_CONTACT_INFORMATION)
	REFERENCES BTS.CONTACT_INFORMATION (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.CUSTOMER
	ADD FOREIGN KEY (FK_PAYMENT_MODE)
	REFERENCES BTS.PAYMENT_MODE (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.CUSTOMER
	ADD FOREIGN KEY (FK_LEGAL_FORM)
	REFERENCES BTS.LEGAL_FORM (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;
