CREATE TABLE CUSTOMER_CONTACT
(
	FK_CUSTOMER BIGINT NOT NULL,
	FK_CONTACT BIGINT NOT NULL,
	PRIMARY KEY (FK_CUSTOMER, FK_CONTACT)
) ENGINE = InnoDB;

ALTER TABLE CUSTOMER_CONTACT
	ADD FOREIGN KEY (FK_CONTACT)
	REFERENCES CONTACT (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE CUSTOMER_CONTACT
	ADD FOREIGN KEY (FK_CUSTOMER)
	REFERENCES CUSTOMER (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;