DROP TABLE IF EXISTS `bts`.`society`;
CREATE TABLE  `bts`.`society` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `LABEL` varchar(100) NOT NULL,
  `CAPITAL` decimal(10,0) NOT NULL,
  `ACTIVITY` varchar(100) NOT NULL,
  `RESPONSIBLE` varchar(100) NOT NULL,
  `FK_ADDRESS` bigint(20) unsigned NOT NULL,
  `FK_LEGAL_FORM` bigint(20) unsigned NOT NULL,
  `FK_CONTACT_INFORMATION` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_ADDRESS` (`FK_ADDRESS`),
  KEY `FK_LEGAL_FORM` (`FK_LEGAL_FORM`),
  KEY `FK_CONTACT_INFORMATION` (`FK_CONTACT_INFORMATION`),
  CONSTRAINT `FK_ADDRESS` FOREIGN KEY (`FK_ADDRESS`) REFERENCES `address` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_LEGAL_FORM` FOREIGN KEY (`FK_LEGAL_FORM`) REFERENCES `legal_form` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `FK_CONTACT_INFORMATION` FOREIGN KEY (`FK_CONTACT_INFORMATION`) REFERENCES `contact_information` (`ID`) ON DELETE CASCADE
) ENGINE=InnoDB;