CREATE TABLE SOCIETY
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	LABEL VARCHAR(100) NOT NULL,
	CAPITAL DECIMAL(10,2) NOT NULL,
	ACTIVITY VARCHAR(100) NOT NULL,
	RESPONSIBLE VARCHAR(100),
	FK_CONTACT_INFORMATION BIGINT NOT NULL,
	FK_ADDRESS BIGINT NOT NULL,
	FK_LEGAL_FORM BIGINT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB;

/* Create Foreign Keys */

ALTER TABLE SOCIETY
	ADD FOREIGN KEY (FK_ADDRESS)
	REFERENCES ADDRESS (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE SOCIETY
	ADD FOREIGN KEY (FK_CONTACT_INFORMATION)
	REFERENCES CONTACT_INFORMATION (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE SOCIETY
	ADD FOREIGN KEY (FK_LEGAL_FORM)
	REFERENCES LEGAL_FORM (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;