//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.21 at 08:29:51 PM CEST 
//


package be.jsams.server.xml.model.estimate;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}society"/>
 *         &lt;element ref="{}customer"/>
 *         &lt;element ref="{}creation_date"/>
 *         &lt;element ref="{}number"/>
 *         &lt;element ref="{}details"/>
 *         &lt;element ref="{}total_et"/>
 *         &lt;element ref="{}vat"/>
 *         &lt;element ref="{}total_ati"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "society",
    "customer",
    "creationDate",
    "number",
    "details",
    "totalEt",
    "vat",
    "totalAti"
})
@XmlRootElement(name = "estimate")
public class EstimateXml {

    @XmlElement(required = true)
    protected SocietyXml society;
    @XmlElement(required = true)
    protected CustomerXml customer;
    @XmlElement(name = "creation_date", required = true)
    @XmlSchemaType(name = "date")
    protected Date creationDate;
    protected int number;
    @XmlElement(required = true)
    protected DetailsXml details;
    @XmlElement(name = "total_et")
    protected double totalEt;
    protected double vat;
    @XmlElement(name = "total_ati")
    protected double totalAti;

    /**
     * Gets the value of the society property.
     * 
     * @return
     *     possible object is
     *     {@link SocietyXml }
     *     
     */
    public SocietyXml getSociety() {
        return society;
    }

    /**
     * Sets the value of the society property.
     * 
     * @param value
     *     allowed object is
     *     {@link SocietyXml }
     *     
     */
    public void setSociety(SocietyXml value) {
        this.society = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerXml }
     *     
     */
    public CustomerXml getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerXml }
     *     
     */
    public void setCustomer(CustomerXml value) {
        this.customer = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link Date}
     *     
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date}
     *     
     */
    public void setCreationDate(Date value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link DetailsXml }
     *     
     */
    public DetailsXml getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailsXml }
     *     
     */
    public void setDetails(DetailsXml value) {
        this.details = value;
    }

    /**
     * Gets the value of the totalEt property.
     * 
     */
    public double getTotalEt() {
        return totalEt;
    }

    /**
     * Sets the value of the totalEt property.
     * 
     */
    public void setTotalEt(double value) {
        this.totalEt = value;
    }

    /**
     * Gets the value of the vat property.
     * 
     */
    public double getVat() {
        return vat;
    }

    /**
     * Sets the value of the vat property.
     * 
     */
    public void setVat(double value) {
        this.vat = value;
    }

    /**
     * Gets the value of the totalAti property.
     * 
     */
    public double getTotalAti() {
        return totalAti;
    }

    /**
     * Sets the value of the totalAti property.
     * 
     */
    public void setTotalAti(double value) {
        this.totalAti = value;
    }

}
