CREATE TABLE BTS.CONTACT_INFORMATION
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	PHONE VARCHAR(50) NOT NULL,
	FAX VARCHAR(50),
	MOBILE VARCHAR(50),
	EMAIL VARCHAR(100),
	WEBSITE VARCHAR(100),
	LOGO LONGBLOB,
	PRIMARY KEY (ID)
) ENGINE = InnoDB;