CREATE TABLE `bts`.`CONTACT_INFORMATION` (
  `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `PHONE` VARCHAR(45) NOT NULL,
  `FAX` VARCHAR(45) NOT NULL,
  `GSM` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `WEBSITE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;
