CREATE TABLE PRODUCT
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	LABEL VARCHAR(100) NOT NULL,
	PRICE REAL(12,2) NOT NULL,
	QUANTITY_STOCK BIGINT NOT NULL,
	REORDER_LEVEL BIGINT,
	VAT_APPLICABLE REAL(5,2) NOT NULL,
	FK_CATEGORY_PRODUCT BIGINT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB;

ALTER TABLE PRODUCT
	ADD FOREIGN KEY (FK_CATEGORY_PRODUCT)
	REFERENCES PRODUCT_CATEGORY (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;