CREATE TABLE BTS.SOCIETY
(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	LABEL VARCHAR(100) NOT NULL,
	CAPITAL REAL(12,2) NOT NULL,
	ACTIVITY VARCHAR(100) NOT NULL,
	RESPONSIBLE VARCHAR(100),
	VAT_NUMBER VARCHAR(100),
	FK_CONTACT_INFORMATION BIGINT NOT NULL,
	FK_ADDRESS BIGINT NOT NULL,
	FK_LEGAL_FORM BIGINT NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB;

ALTER TABLE BTS.SOCIETY
	ADD FOREIGN KEY (FK_ADDRESS)
	REFERENCES BTS.ADDRESS (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.SOCIETY
	ADD FOREIGN KEY (FK_CONTACT_INFORMATION)
	REFERENCES BTS.CONTACT_INFORMATION (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;

ALTER TABLE BTS.SOCIETY
	ADD FOREIGN KEY (FK_LEGAL_FORM)
	REFERENCES BTS.LEGAL_FORM (ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;