INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("CASH", "COMPTANT", "CONTANT", 0, 0, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("TRANSFER", "VIREMENT", "OVERSCHRIJVING", 0, 0, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("CHECK", "CHEQUE", "BANKCHEQUE", 0, 0, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("30 days", "30 jours", "30 dagen", 30, 0, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("60 days", "60 jours", "60 dagen", 60, 0, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("90 days", "90 jours", "90 dagen", 90, 0, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("30 days end of month", "30 jours fin du mois", "30 dagen einde of mand", 30, 1, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("60 days end of month", "60 jours fin du mois", "60 dagen einde of mand", 60, 1, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("90 days end of month", "90 jours fin du mois", "90 dagen einde of mand", 90, 1, 0);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("30 days end of month the 10", "30 jours fin du mois le 10", "30 dagen einde of mand de 10", 30, 1, 10);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("60 days end of month the 10", "60 jours fin du mois le 10", "60 dagen einde of mand de 10", 60, 1, 10);
INSERT INTO BTS.PAYMENT_MODE (LABEL, LABEL_FR, LABEL_NL, DAYS_NUMBER, MONTH_END, ADDITIONAL_DAYS)
VALUES ("90 days end of month the 10", "90 jours fin du mois le 10", "90 dagen einde of mand de 10", 70, 1, 10);