INSERT INTO BTS.CIVILITY (LABEL, LABEL_FR, LABEL_NL)
VALUES ("Mr.", "M.", "Dhr.");
INSERT INTO BTS.CIVILITY (LABEL, LABEL_FR, LABEL_NL)
VALUES ("Ms.", "Mlle.", "Mej.");
INSERT INTO BTS.CIVILITY (LABEL, LABEL_FR, LABEL_NL)
VALUES ("Mrs.", "Mme.", "Mw.");
INSERT INTO BTS.CIVILITY (LABEL, LABEL_FR, LABEL_NL)
VALUES ("Dr.", "Dr.", "Dr.");
INSERT INTO BTS.CIVILITY (LABEL, LABEL_FR, LABEL_NL)
VALUES ("Att.", "Me.", "Mr.");
INSERT INTO BTS.CIVILITY (LABEL, LABEL_FR, LABEL_NL)
VALUES ("Prof.", "Pr.", "Prof.");
